### ISSUE TITLE
Issue due to commas in comments when running mainCombineResults.r 

### ISSUE THREAD

**Issue by ScottZimmerman** [MRCIEU/PHESANT#13]
When running mainCombineResults.r I'm sometimes getting errors due to commas in comments, e.g. in my "results-logistic-binary-all.txt" file, i have a line that starts:

6145#Serious illness, injury or assault to yourself,CAT-MUL, .....

The comma between illness and injury is not interpreted as being part of a comment.

The errors are of the form:
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 2 did not have 7 elements

The error is raised in the file combineResults.R, during the read.table in the loadResult function. Switching to comment.char="#" doesn't fix it.

Manually removing the problematic commas in "results-logistic-binary-all.txt" fixes the problem.

**Comment by louise** [comment]
Hi Scott,

Thanks for raising this. The comment.char argument should be just "", so that R doesn't treat the remainder of the line after the hash as a comment.

The results line from one of my PHESANT scans, for that field and value is:
6145#1,CAT-MUL,134548/15379(149927),0.0200780394906437,-0.00506661985944387,0.0451672791393633,0.117165812649152

... the value after the hash is the numeric data code value rather than the string (the coded values by clicking on the data coding link on this page http://biobank.ctsu.ox.ac.uk/showcase/field.cgi?id=6145). For some reason your input data has the string values rather than the numeric data codes.

I have added a fix to release v0.19, adding quotes around the varName when saving the results in the phenome scan, so commas don't then break the results processing.

Please let me know if you have any further issues.

Best wishes,

Louise
