### ISSUE TITLE
Error when running mainCombineResults.r

### ISSUE THREAD

**Issue by catlisboa** [MRCIEU/PHESANT#15]
Hi Louise, I'm trying to run a PhenomeScan but I keep getting this error when running mainCombineResults.r. 
I previously ran the phenomeScan.r script with my own "trait of interest", "phenofile" (only a few columns from the original ukbiobank data set but according to the instructions) and divided in 20 parts. 
Any ideas/thoughts on why I get this?

```
Warning message:
package 'optparse' was built under R version 3.6.2 
Error in `$<-.data.frame`(`*tmp*`, "Cat1_Title", value = "") : 
  replacement has 1 row, data has 0
Calls: addVariableDescriptions -> $<- -> $<-.data.frame
Execution halted
```

Thank you so much!
Catarina

**Comment by louise** [comment]
Hi Catarina,

The initial warning means you need to re-install the optparse library for the R version you are using.

Thanks for letting me know about this error. Please could you send me your results files and command you are using (louise.millard@bristol.ac.uk) and I'll debug this?

Best wishes,

Louise

**Comment by catlisboa** [comment]
I think, it didn't work because I was using features that were not only in the first assessment. And there are also some new features added, that were not in the first assessment at all (or previous ones, only in the last one), and I think that was causing the errors. Could you fix this?

Thank you very much!
Catarina

**Comment by louise** [comment]
To enable me to help you, you need to provide an example (preferably a minimal working example). If your problem is with the phenome scanning then you should provide a small set of fake data that replicates the problem with real data. If your problem is with the mainCombineResults.r you can just send me your results files from the PHESANT scan and I can debug using those since they are results of associations not sensitive individual level data (or if you don't wish to share them, then you can create a minimal working example for this).
