### ISSUE TITLE
error when running the example

### ISSUE THREAD

**Issue by symnina** [MRCIEU/PHESANT#23]
Hi,
I'm wondering if anyone could help me resolve the following issue. When I ran the example, it showed an error as follows:

Error in getopt_options(object, args) : 
  Error in getopt(spec = spec, opt = args) : 
  "phenofile=“../testWAS/data/phenotypes.csv”" is not a valid option, or does not support an argument
Calls: parse_args -> parse_options -> getopt_options
Execution halted

And here's my codes:
cd WAS
Rscript phenomeScan.r \
--phenofile=“../testWAS/data/phenotypes.csv” \
--traitofinterestfile=“../testWAS/data/exposure.csv” \
--variablelistfile=“../variable-info/outcome-info.tsv” \
--datacodingfile=“../variable-info/data-coding-ordinal-info.csv” \
--traitofinterest=“exposure”\
--resDir=“../results2/“\
--userId=“userId”\
--sensitivity\
--genetic=FALSE\
--partIdx=1\
--numParts=20
Error in getopt_options(object, args) : 
  Error in getopt(spec = spec, opt = args) : 
  "phenofile=“../testWAS/data/phenotypes.csv”" is not a valid option, or does not support an argument
Calls: parse_args -> parse_options -> getopt_options
Execution halted

**Comment by louise** [comment]
The commands to run the test example are here: https://github.com/MRCIEU/PHESANT/tree/master/testWAS

Note that testWAS has its own variable info files, where as the variablelistfile and datacodingfile arguments you have are using the main phesant ones in the variable-info directory.

In the command you supplied the quotes are ” rather than ".

Here is your command, adapted so that it works:
Rscript phenomeScan.r \
--phenofile="../testWAS/data/phenotypes.csv" \
--traitofinterestfile="../testWAS/data/exposure.csv" \
--variablelistfile="../testWAS/variable-lists/outcome-info.tsv" \
--datacodingfile="../testWAS/variable-lists/data-coding-ordinal-info.txt" \
--traitofinterest="exposure" \
--resDir="../results2/" \
--userId="userId" \
--sensitivity \
--genetic=FALSE
